name: "Setup Rust"
description: "Install Rust toolchain and set profile"
runs:
  using: "composite"
  steps:
    - name: Install dependencies and Rust
      shell: bash
      run: |
        SUDO=""
        if [ "`id -u`" -ne 0 ]; then
            SUDO="sudo"
        fi
        if ! command -v curl &> /dev/null; then
            $SUDO apt-get update && $SUDO apt-get install -y curl ca-certificates git build-essential
        fi
        export RUSTUP_HOME="/usr/local/rustup"
        export CARGO_HOME="/usr/local/cargo"
        $SUDO rm -rf /usr/local/rustup /usr/local/cargo
        curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y --default-toolchain stable --profile minimal -c llvm-tools-preview
        /usr/local/cargo/bin/rustup default stable
        /usr/local/cargo/bin/rustup component add rustfmt clippy
        echo "RUSTUP_HOME=/usr/local/rustup" >> $GITHUB_ENV
        echo "CARGO_HOME=/usr/local/cargo" >> $GITHUB_ENV
        echo "/usr/local/cargo/bin" >> $GITHUB_PATH
