name: "Setup Rust Tools"
description: "Install nextest and cargo-llvm-cov"
runs:
  using: "composite"
  steps:
    - name: Install tools
      shell: bash
      run: |
        SUDO=""
        if [ "`id -u`" -ne 0 ]; then
            SUDO="sudo"
        fi
        if ! command -v curl &> /dev/null; then
            $SUDO apt-get update && $SUDO apt-get install -y curl ca-certificates
        fi
        curl -L --proto '=https' --tlsv1.2 -sSf https://github.com/cargo-bins/cargo-binstall/releases/latest/download/cargo-binstall-aarch64-unknown-linux-musl.tgz | tar -xzf - -C /tmp
        $SUDO mv /tmp/cargo-binstall /usr/local/bin/
        /usr/local/cargo/bin/cargo binstall -y cargo-llvm-cov cargo-nextest
