name: 'Setup Rust Tools'
description: 'Install nextest and cargo-llvm-cov'

runs:
  using: "composite"
  steps:
    - name: Install tools
      shell: bash
      env:
        RUSTUP_HOME: /github/workspace/.wrkflw/home/.rustup
        CARGO_HOME: /github/workspace/.wrkflw/cargo-home
      run: |
        if ! command -v curl &> /dev/null; then
            apt-get update && apt-get install -y curl ca-certificates
        fi
        curl -L --proto '=https' --tlsv1.2 -sSf https://raw.githubusercontent.com/cargo-bins/cargo-binstall/main/install-from-binstall-release.sh | bash
        $CARGO_HOME/bin/cargo binstall -y cargo-llvm-cov cargo-nextest
