name: build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  contents: write

jobs:
  build-rust:
    strategy:
      matrix:
        platform: [ubuntu-latest]
    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0
          submodules: recursive
          
      - name: Setup Rust (Custom)
        uses: ./.github/actions/setup-rust
        
      - name: Setup Tools (Custom)
        uses: ./.github/actions/setup-tools
        
      - uses: Swatinem/rust-cache@v2
      
      - name: Check code format
        run: cargo fmt -- --check
        
      - name: Check the package for errors
        run: cargo check --all
        
      - name: Lint rust sources
        run: cargo clippy --all-targets --all-features --tests --benches -- -D warnings
        
      - name: Execute rust tests
        run: |
          SUDO=""
          if [ "`id -u`" -ne 0 ]; then
              SUDO="sudo"
          fi
          if ! command -v cc &> /dev/null; then
              $SUDO apt-get update && $SUDO apt-get install -y build-essential
          fi
          cargo nextest run --all-features
        
      - name: Generate a changelog
        uses: orhun/git-cliff-action@v4
        id: git-cliff
        if: startsWith(github.ref, 'refs/tags/')
        with:
          config: cliff.toml
          args: -vv --latest --strip header
        env:
          OUTPUT: CHANGELOG.md
          
      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          body: ${{ steps.git-cliff.outputs.content }}
